name: Eslint

on:
  pull_request:

jobs:
  eslint:
    name: Eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Build
        uses: ./.github/actions/build

      - name: Lint
        run: pnpm lint -f json -o ./eslint_res.txt

      - name: Create annotations
        run: |
          node ./.github/scripts/eslintAnnotations.js ./eslint_res.txt
